plugin:
    name: 'Multiverse Content Manager'
    description: "A basic content manager which allows you to easily manage the Multiverse theme. \r\nTheme: https://octobercms.com/theme/sliderweb-sliderweb-003-october"
    author: 'Rob VW'
    icon: oc-icon-camera-retro
    homepage: ''
navigation:
    mcm-menu-item:
        label: 'Multiverse Content Management'
        url: robvw/multiversecontentmanager/uploads
        icon: icon-pencil
